name = "statlabinteractive"

compatibility_date = "2025-02-24"
compatibility_flags = ['nodejs_compat']

main = ".worker-next/index.mjs"
assets = {directory = ".worker-next/assets, binding = "ASSETS" }
